//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_1
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Employee_1 Employee_11 { get; set; }
        public virtual Employee_1 Employee_12 { get; set; }
    }
}
